app/config/routes.rb
Rails.application.routes.draw do
  get 'users/main'
  resources :hello_dockers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'
  get "top" => "top#hello"
  get "users" => "users#main"
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/hello_docker.rb
class HelloDocker < ApplicationRecord
end

app/app/models/user.rb
class User < ApplicationRecord
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/hello_dockers_controller.rb
class HelloDockersController < ApplicationController
  before_action :set_hello_docker, only: [:show, :edit, :update, :destroy]

  # GET /hello_dockers
  # GET /hello_dockers.json
  def index
    @hello_dockers = HelloDocker.all
  end

  # GET /hello_dockers/1
  # GET /hello_dockers/1.json
  def show
  end

  # GET /hello_dockers/new
  def new
    @hello_docker = HelloDocker.new
  end

  # GET /hello_dockers/1/edit
  def edit
  end

  # POST /hello_dockers
  # POST /hello_dockers.json
  def create
    @hello_docker = HelloDocker.new(hello_docker_params)

    respond_to do |format|
      if @hello_docker.save
        format.html { redirect_to @hello_docker, notice: 'Hello docker was successfully created.' }
        format.json { render :show, status: :created, location: @hello_docker }
      else
        format.html { render :new }
        format.json { render json: @hello_docker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hello_dockers/1
  # PATCH/PUT /hello_dockers/1.json
  def update
    respond_to do |format|
      if @hello_docker.update(hello_docker_params)
        format.html { redirect_to @hello_docker, notice: 'Hello docker was successfully updated.' }
        format.json { render :show, status: :ok, location: @hello_docker }
      else
        format.html { render :edit }
        format.json { render json: @hello_docker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hello_dockers/1
  # DELETE /hello_dockers/1.json
  def destroy
    @hello_docker.destroy
    respond_to do |format|
      format.html { redirect_to hello_dockers_url, notice: 'Hello docker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hello_docker
      @hello_docker = HelloDocker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hello_docker_params
      params.require(:hello_docker).permit(:name)
    end
end

app/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @hello = "hey"
  end

  def hello
    @hello = "aloha"
    render("index")
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def main
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/hello_dockers_helper.rb
module HelloDockersHelper
end

app/app/helpers/top_helper.rb
module TopHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/hello_dockers/_form.html.erb
<%= form_with(model: hello_docker, local: true) do |form| %>
  <% if hello_docker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hello_docker.errors.count, "error") %> prohibited this hello_docker from being saved:</h2>

      <ul>
      <% hello_docker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/hello_dockers/edit.html.erb
<h1>Editing Hello Docker</h1>

<%= render 'form', hello_docker: @hello_docker %>

<%= link_to 'Show', @hello_docker %> |
<%= link_to 'Back', hello_dockers_path %>

app/app/views/hello_dockers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hello Dockers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hello_dockers.each do |hello_docker| %>
      <tr>
        <td><%= hello_docker.name %></td>
        <td><%= link_to 'Show', hello_docker %></td>
        <td><%= link_to 'Edit', edit_hello_docker_path(hello_docker) %></td>
        <td><%= link_to 'Destroy', hello_docker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hello Docker', new_hello_docker_path %>

app/app/views/hello_dockers/new.html.erb
<h1>New Hello Docker</h1>

<%= render 'form', hello_docker: @hello_docker %>

<%= link_to 'Back', hello_dockers_path %>

app/app/views/hello_dockers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hello_docker.name %>
</p>

<%= link_to 'Edit', edit_hello_docker_path(@hello_docker) %> |
<%= link_to 'Back', hello_dockers_path %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/app/views/top/index.html.erb
top#index
<%
 a = @hello

 if(a=="hey")
   b = "hey!!!!!!"
 elsif(a=="aloha")
   b = "ここはハワイではありません"
 end

 %>

<%= b %>

app/app/views/users/main.html.erb
<h1>Users#main</h1>
<p>Find me in app/views/users/main.html.erb</p>